baseURL = 'https://example.org/'
languageCode = 'en-gb'
title = 'Graphiti Manual'
enableGitInfo = true

[markup.goldmark.renderer]
  unsafe= true

[markup.goldmark.extensions.passthrough]
  enable = true

[markup.goldmark.extensions.passthrough.delimiters]
  block = [['\[', '\]'], ['$$', '$$']]
  inline = [['\(', '\)']]

[markup.tableOfContents]
  endLevel = 2
  ordered = false
  startLevel = 2

[frontmatter]
  lastmod = ["lastmod", ":git", "date", "publishDate"]
